# -*- coding: utf-8 -*-
"""05_conclusionesfinales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2G-nbhVpeIhWj9f_WbY_TCAfHlXBHZU

# **Conclusiones finales del Proyecto Integrador**

**El análisis del dataset** streaming_users_dirty.json permitió aplicar de manera práctica los contenidos de Minería de Datos 1, siguiendo un flujo ordenado de inspección, preparación, exploración y reducción de dimensionalidad.

**Calidad de datos**: La inspección inicial evidenció valores faltantes y registros duplicados, que fueron corregidos mediante imputación y limpieza. Esto garantizó un dataset confiable para el análisis.

**Patrones de consumo**: El análisis exploratorio mostró que los usuarios jóvenes tienden a dedicar más horas al streaming, mientras que las diferencias entre plataformas y países sugieren que las preferencias culturales y la oferta de contenido influyen en los hábitos de uso.

**Relaciones entre variables**: La matriz de correlación confirmó vínculos significativos entre edad, horas de uso y tiempo de suscripción, lo que permitió identificar segmentos de usuarios con comportamientos similares.

**Reducción de dimensionalidad (PCA)**: Los dos primeros componentes principales explicaron gran parte de la varianza del dataset. El PC1 estuvo influido principalmente por edad y horas de uso, mientras que el PC2 reflejó diferencias asociadas a plataforma y país. La visualización PCA permitió identificar agrupamientos claros de usuarios.

**Conclusión general**: El proyecto cumplió con los objetivos planteados: decisiones justificadas, trazabilidad del proceso y comunicación clara de resultados. La integración con Streamlit facilitó la interpretación visual y reforzó la transparencia del trabajo, convirtiéndolo en una herramienta interactiva y reproducible.
"""