# -*- coding: utf-8 -*-
"""Mineria_datos1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwON8GR3Dlrp70Z99-ZrbPwLRNEOk6Kb
"""

!pip install streamlit

import streamlit as st

st.set_page_config(
    page_title="Minería de Datos I",
    page_icon="🧠",
    layout="wide"
)

# 2. TÍTULO PRINCIPAL DE LA APP
st.title("🚀 Proyecto Integrador: Minería de Datos I")

# 3. INTRODUCCIÓN
st.markdown("""
### ¡Bienvenido a nuestra plataforma de análisis!
Este proyecto fue diseñado para aplicar técnicas avanzadas de *Minería de Datos* sobre nuestro dataset.
A través del menú lateral izquierdo, podrás navegar por las distintas fases del pipeline de datos: desde la inspección inicial hasta la reducción de dimensionalidad.
""")

# Un separador visual
st.divider()

# 4. EXPLICACIÓN DE LAS PÁGINAS
st.subheader("📁 ")

col1, col2 = st.columns(2)

with col1:
    st.info("📊 *01. Dataset & EDA*\n\nExplora la estructura de los datos crudos y visualiza los gráficos estadísticos clave de las variables.")

with col2:
    st.success("🧬 *02. PCA & Conclusiones*\n\nAnaliza el impacto de la reducción de dimensiones y revisa los hallazgos finales del modelo.")

# 5. INTEGRANTES
st.sidebar.markdown("### 👥 Integrantes del Grupo")
st.sidebar.write("- Cordoba_Maria de los Angeles")
st.sidebar.write("- Mansilla Fatima")
